#!/bin/bash
# 一键:从 D1 刷新所有已转飞书多维表。本月 scraper 飞书 app 配额死,cron 写不动,用这个手动刷。
# 用法: bash ~/tiktok-scraper/d1sync/refresh-all.sh
A=~/tiktok-analytics; D=~/tiktok-scraper/d1sync
cd "$A"
q(){ for t in 1 2 3; do npx wrangler d1 execute tiktok-analytics --remote --json --command "$1" > "$2" 2>/dev/null && python3 -c "import json;d=json.load(open('$2'));exit(0 if isinstance(d,list) else 1)" && return 0; sleep 3; done; echo "FAIL $2"; }
echo "[1/2] 从 D1 重生成数据文件…"
q "SELECT stat_date, ROUND(spend,1) sp, ROUND(revenue,1) rev, ROUND(weighted_roas,4) adroi, new_users nu, ROUND(cum_spend,1) cs, ROUND(cum_revenue,1) cr, ROUND(cum_roi,4) croi FROM daily_summary ORDER BY stat_date" /tmp/ds_all.json
q "SELECT a.stat_date sd, MAX(g.group_name) grp, a.game game, ROUND(SUM(a.spend),1) sp, CASE WHEN SUM(a.spend)>0 THEN ROUND(SUM(a.spend*a.roas)/SUM(a.spend),4) END roas, ROUND(SUM(CASE WHEN a.bid_type='手动出价' THEN a.spend ELSE 0 END),1) msp, CASE WHEN SUM(CASE WHEN a.bid_type='手动出价' THEN a.spend ELSE 0 END)>0 THEN ROUND(SUM(CASE WHEN a.bid_type='手动出价' THEN a.spend*a.roas ELSE 0 END)/SUM(CASE WHEN a.bid_type='手动出价' THEN a.spend ELSE 0 END),4) END mroi, ROUND(SUM(CASE WHEN a.bid_type='自动出价' THEN a.spend ELSE 0 END),1) asp, CASE WHEN SUM(CASE WHEN a.bid_type='自动出价' THEN a.spend ELSE 0 END)>0 THEN ROUND(SUM(CASE WHEN a.bid_type='自动出价' THEN a.spend*a.roas ELSE 0 END)/SUM(CASE WHEN a.bid_type='自动出价' THEN a.spend ELSE 0 END),4) END aroi, SUM(a.gross_impressions) gross, SUM(a.first_launch) fl FROM ads_raw a LEFT JOIN games g ON g.game=a.game GROUP BY a.stat_date, a.game" /tmp/ads_game.json
q "SELECT p.stat_date sd, g.group_name grp, p.game game, p.new_users nu, p.active_users au, ROUND(p.ad_revenue,2) rev, p.portal_json pj FROM products_raw p LEFT JOIN games g ON g.game=p.game WHERE p.portal_json IS NOT NULL" /tmp/prod_game.json
q "SELECT stat_date sd, game, ROUND(ad_revenue,2) rev FROM products_raw" /tmp/prod_rev.json
q "SELECT a.stat_date sd, MAX(g.group_name) grp, a.game game, a.bid_type bt, ROUND(SUM(a.spend),1) sp, CASE WHEN SUM(a.spend)>0 THEN ROUND(SUM(a.spend*a.roas)/SUM(a.spend),4) END roas, SUM(a.first_launch) fl, SUM(a.gross_impressions) gross FROM ads_raw a LEFT JOIN games g ON g.game=a.game GROUP BY a.stat_date, a.game, a.bid_type HAVING sp>0" /tmp/ads_bid.json
q "SELECT stat_date sd, ROUND(spend,1) sp, ROUND(revenue,1) rev, ROUND(weighted_roas,4) adroi, ROUND(revenue_roi,4) yroi, ROUND(cum_roi,4) croi, new_users nu, pending FROM daily_summary WHERE stat_date >= date((SELECT MAX(stat_date) FROM daily_summary),'-8 day') ORDER BY stat_date" /tmp/ye_total.json
q "SELECT stat_date sd, group_name grp, ROUND(spend,1) sp, ROUND(revenue,1) rev, ROUND(weighted_roas,4) adroi, ROUND(cum_roi,4) croi, new_users nu, ROUND(manual_spend,1) msp, ROUND(manual_roi,4) mroi, ROUND(auto_spend,1) asp, ROUND(auto_roi,4) aroi FROM project_daily WHERE stat_date >= date((SELECT MAX(stat_date) FROM project_daily),'-8 day') ORDER BY stat_date" /tmp/ye_proj.json
q "SELECT a.stat_date sd, MAX(g.group_name) grp, a.game game, ROUND(SUM(a.spend),1) sp, CASE WHEN SUM(a.spend)>0 THEN ROUND(SUM(a.spend*a.roas)/SUM(a.spend),4) END roas, SUM(a.first_launch) fl, ROUND(SUM(CASE WHEN a.bid_type='手动出价' THEN a.spend ELSE 0 END),1) msp, CASE WHEN SUM(CASE WHEN a.bid_type='手动出价' THEN a.spend ELSE 0 END)>0 THEN ROUND(SUM(CASE WHEN a.bid_type='手动出价' THEN a.spend*a.roas ELSE 0 END)/SUM(CASE WHEN a.bid_type='手动出价' THEN a.spend ELSE 0 END),4) END mroi, ROUND(SUM(CASE WHEN a.bid_type='自动出价' THEN a.spend ELSE 0 END),1) asp, CASE WHEN SUM(CASE WHEN a.bid_type='自动出价' THEN a.spend ELSE 0 END)>0 THEN ROUND(SUM(CASE WHEN a.bid_type='自动出价' THEN a.spend*a.roas ELSE 0 END)/SUM(CASE WHEN a.bid_type='自动出价' THEN a.spend ELSE 0 END),4) END aroi FROM ads_raw a LEFT JOIN games g ON g.game=a.game WHERE a.stat_date >= date((SELECT MAX(stat_date) FROM ads_raw),'-1 day') GROUP BY a.stat_date, a.game HAVING sp>0 ORDER BY a.stat_date" /tmp/ye_game.json
q "SELECT stat_date sd, game, ROUND(ad_revenue,2) rev, new_users nu FROM products_raw WHERE stat_date >= date((SELECT MAX(stat_date) FROM products_raw),'-8 day')" /tmp/ye_prodrev.json
q "SELECT a.stat_date sd, a.material mat, MAX(g.group_name) grp, ROUND(SUM(a.spend),1) sp, CASE WHEN SUM(a.spend)>0 THEN ROUND(SUM(a.spend*a.roas)/SUM(a.spend),4) END roas, ROUND(SUM(CASE WHEN a.bid_type='手动出价' THEN a.spend ELSE 0 END),1) msp, CASE WHEN SUM(CASE WHEN a.bid_type='手动出价' THEN a.spend ELSE 0 END)>0 THEN ROUND(SUM(CASE WHEN a.bid_type='手动出价' THEN a.spend*a.roas ELSE 0 END)/SUM(CASE WHEN a.bid_type='手动出价' THEN a.spend ELSE 0 END),4) END mroi, ROUND(SUM(CASE WHEN a.bid_type='自动出价' THEN a.spend ELSE 0 END),1) asp, CASE WHEN SUM(CASE WHEN a.bid_type='自动出价' THEN a.spend ELSE 0 END)>0 THEN ROUND(SUM(CASE WHEN a.bid_type='自动出价' THEN a.spend*a.roas ELSE 0 END)/SUM(CASE WHEN a.bid_type='自动出价' THEN a.spend ELSE 0 END),4) END aroi, SUM(a.impressions) imp, SUM(a.clicks) clk, SUM(a.gross_impressions) gross, SUM(a.first_launch) fl FROM ads_raw a LEFT JOIN games g ON g.game=a.game WHERE a.stat_date >= date((SELECT MAX(stat_date) FROM ads_raw),'-29 day') AND a.material!='' GROUP BY a.stat_date, a.material HAVING sp>0" /tmp/ads_mat.json
q "SELECT a.game game, MAX(g.group_name) grp, ROUND(SUM(a.spend),1) sp, ROUND(SUM(CASE WHEN a.bid_type='手动出价' THEN a.spend ELSE 0 END),1) msp, ROUND(SUM(CASE WHEN a.bid_type='自动出价' THEN a.spend ELSE 0 END),1) asp FROM ads_raw a LEFT JOIN games g ON g.game=a.game WHERE a.stat_date>='2026-04-01' GROUP BY a.game HAVING sp>0" /tmp/q2_ads.json
q "SELECT game, ROUND(SUM(ad_revenue),1) rev FROM products_raw WHERE stat_date>='2026-04-01' GROUP BY game" /tmp/q2_rev.json
echo "[2/2] 同步飞书表(日汇总/包体/项目维度/投放日报产品+出价/昨日速览×3/素材)…"
for s in sync_daily sync_baoti sync_xmwd sync_tfprod sync_tfbid sync_yesterday sync_mat sync_indep sync_q2; do echo "  → $s"; python3 "$D/$s.py" 2>&1 | tail -1; done
echo "✅ 全部已转飞书表已从 D1 刷新到最新"
